### ISSUE TITLE
Latest version (1.4.0) not working

### ISSUE THREAD

**Issue by den7007** [libredirect/libredirect#55]
Using it on a linux machine (POP OS) running Firefox.

Settings do not save whether via the toolbar pop up or options page. 

Instances list is not displayed for YouTube or Twitter.

![02-21-2022_1](https://user-images.githubusercontent.com/68644291/154902745-326fb857-2bfc-47b7-8aa9-54709bc11ab5.jpg)

I tried adding a custom instance too but it does not show up.

All redirects, even when enabled, are not working.

**Comment by Latrolage** [comment]
I had this problem after the update. My hotfix was to refresh the firefox profile, though it probably should be fixed

**Comment by den7007** [comment]
> I had this problem after the update. My hotfix was to refresh the firefox profile, though it probably should be fixed

Thanks, a refresh fixed it, hope this won't be needed moving forward!

**Comment by den7007** [comment]
Just noticed these now:

- some settings are still not being saved, such as Theme and Autoplay Video under YouTube

- may be specific to Piped, but channel links like youtube.com/username are redirected to piped.kavin.rocks/username, but it should be piped.kavin.rocks/c/username

For channel links that have a string such as  youtube.com/channel/UCjCecOXpBueoVOz28E1UGew , can be redirected to piped.kavin.rocks/channel/UCjCecOXpBueoVOz28E1UGew

**Comment by stephenhawk8054** [comment]
Yeah, I have the same problem, don't know what to do now because I don't want to reset my profiles. Install in new profile has no problems.

**Comment by xfzv** [comment]
> Yeah, I have the same problem, but on Windows 10, don't know what to do now because I don't want to reset my profile. Install in new profile has no problems.

Same here, I've just noticed it stopped working. No way I refresh my Firefox profile, this should be properly fixed.

**Comment by ManeraKai** [comment]
@xfzv There are no errors to begin debugging and fixing the problemin the first place.
Try this one: https://support.mozilla.org/en-US/kb/refresh-firefox-reset-add-ons-and-settings

**Comment by ManeraKai** [comment]
Looking more through and there's some problem with `browser.storage.sync`. We've changed to `browser.storage.local`. This will prevent syncing the settings between multiple devices that have the same account.

**Comment by ManeraKai** [comment]
Released a new version. You can update it now from the https://addons.mozilla.org but your old settings won't be updated as we've migrated to a new storage structure that is `local`. The old one was `sync`.

**Comment by xfzv** [comment]
Thank you @ManeraKai, can confirm everything works as expected now after updating to 1.4.1.
