### ISSUE TITLE
Stop opening a new tab for the settings

### ISSUE THREAD

**Issue by jamesWalker55** [libredirect/libredirect#625]
LibRedirect now randomly creates a new tab showing its settings. It consistently opens a new tab when I first open the browser, then happens rarely during prolonged usage.

**Comment by ManeraKai** [comment]
I fixed this now, it will only open the settings page when it "installs", previously it did after it "installed" and after it "updated". I will push the change today from my local machine.

**Comment by sylentpunk** [comment]
I'm still getting this issue on librewolf. in about:extensions, it says the extension version is 2.5.2, librewolf is version 110.0-2.

**Comment by ManeraKai** [comment]
I fixed it a day after releasing 2.5.2.

**Comment by sylentpunk** [comment]
ah i see, my bad

**Comment by jamesWalker55** [comment]
I am still encountering this bug. When I close the browser completely then open it again, LibRedirect still opens a new tab showing the settings upon startup.

I am on Libredirect 2.5.2, Firefox 110.0.1.

**Comment by IkelAtomig** [comment]
@jamesWalker55 Please wait. v2.5.3 of the extension is finalized and should be available in a day or two for release.
